---

#Gerenciamento de pacotes e atualização do SO
- name: Atualizacao do Sistema Operacional
  yum: name=* state=latest update_cache=yes

# Instalação de Pacotes
- name: Instalacao de Pacotes
  yum: 
    name: "{{ packages}}"
    state: latest
  vars: 
    packages:
      - net-tools
      - vim

# Configuração de Timezone
- name: Configurando Timezone
  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes 

...
